export const PIPELINE_STATUS = {
  RECEIVED: "received",
  HTML_READY: "html_ready",
  HTML_UNAVAILABLE: "html_unavailable",
  HTML_SNAPSHOT_MISMATCH: "html_snapshot_mismatch",
  MATCHING: "matching",
  MATCHED: "matched",
  MATCH_FAILED: "match_failed",
  PDF_READY: "pdf_ready",
  PDF_NOT_FOUND: "pdf_not_found",
  PDF_AMBIGUOUS: "pdf_ambiguous",
  PDF_FAILED: "pdf_failed",
  PDF_INVALID: "pdf_invalid",
  TEXT_EXTRACTING: "text_extracting",
  QUALITY_GATE: "quality_gate",
  EXTRACTION_FAILED: "extraction_failed",
  AI_PROCESSING: "ai_processing",
  AI_READY: "ai_ready",
  AI_FAILED: "ai_failed",
  VALIDATING: "validating",
  VALIDATION_FAILED: "validation_failed",
  PENDING_REVIEW: "pending_review",
  PUBLISHING: "publishing",
  PUBLISHED: "published",
  REJECTED: "rejected",
  DUPLICATE: "duplicate",
  NOTIFICATION_DUPLICATE: "notification_duplicate",
  PUBLISH_FAILED: "publish_failed",
};

export const PIPELINE_STATUS_LIST = Object.values(PIPELINE_STATUS);
