import { Bodies } from "../models/Bodies.js";

export const seedBodies = async () => {
    await Bodies.deleteMany();
    await Bodies.insertMany([
  { name: "Staff Selection Commission SSC", slug: "staff-selection-commission-ssc" },
  { name: "Andhra Pradesh Public Service Commission APPSC", slug: "andhra-pradesh-public-service-commission-appsc" },
  { name: "Assam Public Service Commission APSC", slug: "assam-public-service-commission-apsc" },
  { name: "Bihar Public Service Commission BPSC", slug: "bihar-public-service-commission-bpsc" },
  { name: "Gujarat Public Service Commission GPSC", slug: "gujarat-public-service-commission-gpsc" },
  { name: "Himachal Pradesh Public Service Commission HPPSC", slug: "himachal-pradesh-public-service-commission-hppsc" },
  { name: "Haryana Public Service Commission HPSC", slug: "haryana-public-service-commission-hpsc" },
  { name: "Jharkhand Public Service Commission JPSC", slug: "jharkhand-public-service-commission-jpsc" },
  { name: "Karnataka Public Service Commission KPSC", slug: "karnataka-public-service-commission-kpsc" },
  { name: "Kerala Public Service Commission Keralapsc", slug: "kerala-public-service-commission-keralapsc" },
  { name: "Madhya Pradesh Public Service Commission MPPSC", slug: "madhya-pradesh-public-service-commission-mppsc" },
  { name: "Maharashtra Public Service Commission MPSC", slug: "maharashtra-public-service-commission-mpsc" },
  { name: "Odisha Public Service Commission OPSC", slug: "odisha-public-service-commission-opsc" },
  { name: "Rajasthan Public Service Commission RPSC", slug: "rajasthan-public-service-commission-rpsc" },
  { name: "Tamil Nadu Public Service Commission TNPSC", slug: "tamil-nadu-public-service-commission-tnpsc" },
  { name: "Telangana State Public Service Commission TSPSC", slug: "telangana-state-public-service-commission-tspsc" },
  { name: "Uttarakhand Public Service Commission UKPSC", slug: "uttarakhand-public-service-commission-ukpsc" },
  { name: "Uttar Pradesh Public Service Commission UPPSC", slug: "uttar-pradesh-public-service-commission-uppsc" },
  { name: "West Bengal Public Service Commission WBPSC", slug: "west-bengal-public-service-commission-wbpsc" },
  { name: "Jammu and Kashmir Public Service Commission JKPSC", slug: "jammu-and-kashmir-public-service-commission-jkpsc" },
  { name: "Manipur Public Service Commission MPSC", slug: "manipur-public-service-commission-mpsc" },
  { name: "Meghalaya Public Service Commission MPSC", slug: "meghalaya-public-service-commission-mpsc" },
  { name: "Mizoram Public Service Commission MPSC", slug: "mizoram-public-service-commission-mpsc" },
  { name: "Nagaland Public Service Commission NPSC", slug: "nagaland-public-service-commission-npsc" },
  { name: "Punjab Public Service Commission PPSC", slug: "punjab-public-service-commission-ppsc" },
  { name: "Sikkim Public Service Commission SPSC", slug: "sikkim-public-service-commission-spsc" },
  { name: "Tripura Public Service Commission TPSC", slug: "tripura-public-service-commission-tpsc" },
  { name: "Joint State Public Service Commission JSPSC", slug: "joint-state-public-service-commission-jspsc" },
  { name: "Arunachal Pradesh Public Service Commission APSC", slug: "arunachal-pradesh-public-service-commission-apsc" },
  { name: "Indian Council of Agricultural Research ICAR", slug: "indian-council-of-agricultural-research-icar" },
  { name: "Central Fertilizer Quality Control and Training Institute", slug: "central-fertilizer-quality-control-and-training-institute" },
  { name: "Directorate of Arecanut and Spices Development DSAD", slug: "directorate-of-arecanut-and-spices-development-dsad" },
  { name: "Directorate of Cashewnut and Cocoa Development DCCD", slug: "directorate-of-cashewnut-and-cocoa-development-dccd" },
  { name: "Directorate of Economics and Statistics DES", slug: "directorate-of-economics-and-statistics-des" },
  { name: "Directorate of Jute Development", slug: "directorate-of-jute-development" },
  { name: "Directorate of Marketing and Inspection DMI", slug: "directorate-of-marketing-and-inspection-dmi" },
  { name: "Directorate of Plant Protection Quarantine and Storage", slug: "directorate-of-plant-protection-quarantine-and-storage" },
  { name: "Directorate of Pulses Development", slug: "directorate-of-pulses-development" },
  { name: "Directorate of Rice Development", slug: "directorate-of-rice-development" },
  { name: "KRISHI VISTAR Directorate of Extension", slug: "krishi-vistar-directorate-of-extension" },
  { name: "Mahalanobis National Crop Forecast Centre NCFC", slug: "mahalanobis-national-crop-forecast-centre-ncfc" },
  { name: "National Seed Research and Training Centre NSRTC", slug: "national-seed-research-and-training-centre-nsrtc" },
  { name: "North Eastern Farm Machinery Training and Testing Institute", slug: "north-eastern-farm-machinery-training-and-testing-institute" },
  { name: "Northern Farm Machinery Training and Testing Institute", slug: "northern-farm-machinery-training-and-testing-institute" },
  { name: "Southern Region Farm Machinery Training and Testing Institute", slug: "southern-region-farm-machinery-training-and-testing-institute" },
  { name: "Soil and Land Use Survey of India", slug: "soil-and-land-use-survey-of-india" },
  { name: "Protection of Plant Varieties and Farmers Rights Authority", slug: "protection-of-plant-varieties-and-farmers-rights-authority" },
  { name: "Central Integrated Pest Management Centre CIPMC", slug: "central-integrated-pest-management-centre-cipmc" },
  { name: "Agrinnovate India", slug: "agrinnovate-india" },
  { name: "Central Council for Research in Ayurvedic Sciences CCRAS", slug: "central-council-for-research-in-ayurvedic-sciences-ccras" },
  { name: "Central Council for Research in Homoeopathy CCRH", slug: "central-council-for-research-in-homoeopathy-ccrh" },
  { name: "Central Council for Research in Siddha CCRS", slug: "central-council-for-research-in-siddha-ccrs" },
  { name: "Central Council for Research in Unani Medicine CCRUM", slug: "central-council-for-research-in-unani-medicine-ccrum" },
  { name: "Central Council for Research in Yoga and Naturopathy CCRYN", slug: "central-council-for-research-in-yoga-and-naturopathy-ccryn" },
  { name: "Rashtriya Ayurveda Vidyapeeth", slug: "rashtriya-ayurveda-vidyapeeth" },
  { name: "Indian Medicines Pharmaceutical Corporation Limited IMPCL", slug: "indian-medicines-pharmaceutical-corporation-limited-impcl" },
  { name: "Coal Controller's Organization", slug: "coal-controller's-organization" },
  { name: "Export Inspection Council EIC", slug: "export-inspection-council-eic" },
  { name: "Export Inspection Agency Delhi", slug: "export-inspection-agency-delhi" },
  { name: "Export Inspection Agency Kolkata", slug: "export-inspection-agency-kolkata" },
  { name: "Export Inspection Agency Kochi", slug: "export-inspection-agency-kochi" },
  { name: "Export Inspection Agency Mumbai", slug: "export-inspection-agency-mumbai" },
  { name: "Export Inspection Agency Chennai", slug: "export-inspection-agency-chennai" },
  { name: "Export Inspection Agency Kakinada", slug: "export-inspection-agency-kakinada" },
  { name: "Controller General of Defence Accounts CGDA", slug: "controller-general-of-defence-accounts-cgda" },
  { name: "Earth System Science Organization ESSO", slug: "earth-system-science-organization-esso" },
  { name: "National Foundation for Communal Harmony NFCH", slug: "national-foundation-for-communal-harmony-nfch" },
  { name: "Repatriates Co-operative Finance and Development Bank Limited", slug: "repatriates-co-operative-finance-and-development-bank-limited" },
  { name: "Northern Regional Power Committee", slug: "northern-regional-power-committee" },
  { name: "Southern Regional Power Committee", slug: "southern-regional-power-committee" },
  { name: "Western Regional Power Committee WRPC", slug: "western-regional-power-committee-wrpc" },
  { name: "Department of Statistics", slug: "department-of-statistics" },
  { name: "Department of Programme Implementation", slug: "department-of-programme-implementation" },
  { name: "Textiles Committee", slug: "textiles-committee" },
  { name: "Central Silk Board", slug: "central-silk-board" },
  { name: "Northern India Textile Research Association NITRA", slug: "northern-india-textile-research-association-nitra" },
  { name: "Ahmedabad Textile Industry's Research Association ATIRA", slug: "ahmedabad-textile-industry's-research-association-atira" },
  { name: "Bombay Textile Research Association BTRA", slug: "bombay-textile-research-association-btra" },
  { name: "South India Textile Research Association SITRA", slug: "south-india-textile-research-association-sitra" },
  { name: "Jute Industry's Research Association IJIRA", slug: "jute-industry's-research-association-ijira" },
  { name: "Wool Research Association WRA", slug: "wool-research-association-wra" },
  { name: "The Synthetic and Art Silk Mills Research Association SASMIRA", slug: "the-synthetic-and-art-silk-mills-research-association-sasmira" },
  { name: "Man-made Textile Research Association MANTRA", slug: "man-made-textile-research-association-mantra" },
  { name: "Rashtriya Mahila Kosh RMK", slug: "rashtriya-mahila-kosh-rmk" },
  { name: "Directorate of Construction Services and Estate Management DCSEM", slug: "directorate-of-construction-services-and-estate-management-dcsem" },
  { name: "Directorate of Purchase and Stores DPS", slug: "directorate-of-purchase-and-stores-dps" },
  { name: "General Services Organisation GSO", slug: "general-services-organisation-gso" },
  { name: "Bhabha Atomic Research Centre BARC", slug: "bhabha-atomic-research-centre-barc" },
  { name: "Atomic Energy Regulatory Board AERB", slug: "atomic-energy-regulatory-board-aerb" },
  { name: "Uranium Corporation of India UCIL", slug: "uranium-corporation-of-india-ucil" },
  { name: "National Dairy Development Board NDDB", slug: "national-dairy-development-board-nddb" },
  { name: "Central Institute for Cotton Research", slug: "central-institute-for-cotton-research" },
  { name: "Directorate General of Civil Aviation DGCA", slug: "directorate-general-of-civil-aviation-dgca" },
  { name: "Airports Authority of India AAI", slug: "airports-authority-of-india-aai" },
  { name: "Coal India Limited CIL", slug: "coal-india-limited-cil" },
  { name: "Central Mine Planning and Design Institute CMPDI", slug: "central-mine-planning-and-design-institute-cmpdi" },
  { name: "Directorate General of Foreign Trade DGFT", slug: "directorate-general-of-foreign-trade-dgft" },
  { name: "Indian Institute of Packaging IIP", slug: "indian-institute-of-packaging-iip" },
  { name: "Bharat Sanchar Nigam Limited BSNL", slug: "bharat-sanchar-nigam-limited-bsnl" },
  { name: "Telecom Regulatory Authority of India TRAI", slug: "telecom-regulatory-authority-of-india-trai" },
  { name: "India Post Payments Bank IPPB", slug: "india-post-payments-bank-ippb" },
  { name: "Bureau of Indian Standards BIS", slug: "bureau-of-indian-standards-bis" },
  { name: "National Consumer Disputes Redressal Commission NCDRC", slug: "national-consumer-disputes-redressal-commission-ncdrc" },
  { name: "National Cooperative Development Corporation NCDC", slug: "national-cooperative-development-corporation-ncdc" },
  { name: "Serious Fraud Investigation Office SFIO", slug: "serious-fraud-investigation-office-sfio" },
  { name: "Institute of Company Secretaries of India ICSI", slug: "institute-of-company-secretaries-of-india-icsi" },
  { name: "Archaeological Survey of India ASI", slug: "archaeological-survey-of-india-asi" },
  { name: "Sahitya Akademi", slug: "sahitya-akademi" },
  { name: "Zonal Cultural Centres", slug: "zonal-cultural-centres" },
  { name: "Defence Research and Development Organisation DRDO", slug: "defence-research-and-development-organisation-drdo" },
  { name: "Border Roads Organisation BRO", slug: "border-roads-organisation-bro" },
  { name: "Directorate General of Quality Assurance DGQA", slug: "directorate-general-of-quality-assurance-dgqa" },
  { name: "Canteen Stores Department CSD", slug: "canteen-stores-department-csd" },
  { name: "North Eastern Development Finance Corporation NEDFi", slug: "north-eastern-development-finance-corporation-nedfi" },
  { name: "Indian Meteorological Department IMD", slug: "indian-meteorological-department-imd" },
  { name: "National Centre for Polar and Ocean Research NCPOR", slug: "national-centre-for-polar-and-ocean-research-ncpor" },
  { name: "University Grants Commission UGC", slug: "university-grants-commission-ugc" },
  { name: "All India Council for Technical Education AICTE", slug: "all-india-council-for-technical-education-aicte" },
  { name: "Central Board of Secondary Education CBSE", slug: "central-board-of-secondary-education-cbse" },
  { name: "National Council of Educational Research and Training NCERT", slug: "national-council-of-educational-research-and-training-ncert" },
  { name: "National Informatics Centre NIC", slug: "national-informatics-centre-nic" },
  { name: "Centre for Development of Advanced Computing C-DAC", slug: "centre-for-development-of-advanced-computing-c-dac" },
  { name: "Software Technology Parks of India STPI", slug: "software-technology-parks-of-india-stpi" },
  { name: "Bhaskaracharya National Institute for Space Applications and Geo-informatics BISAG-N", slug: "bhaskaracharya-national-institute-for-space-applications-and-geo-informatics-bisag-n" },
  { name: "Central Pollution Control Board CPCB", slug: "central-pollution-control-board-cpcb" },
  { name: "Wildlife Institute of India WII", slug: "wildlife-institute-of-india-wii" },
  { name: "National Board for Wildlife NBWL", slug: "national-board-for-wildlife-nbwl" },
  { name: "Indian Council for Cultural Relations ICCR", slug: "indian-council-for-cultural-relations-iccr" },
  { name: "Indian Council of World Affairs ICWA", slug: "indian-council-of-world-affairs-icwa" },
  { name: "Central Board of Direct Taxes CBDT", slug: "central-board-of-direct-taxes-cbdt" },
  { name: "Central Board of Indirect Taxes and Customs CBIC", slug: "central-board-of-indirect-taxes-and-customs-cbic" },
  { name: "Securities and Exchange Board of India SEBI", slug: "securities-and-exchange-board-of-india-sebi" },
  { name: "Insurance Regulatory and Development Authority of India IRDAI", slug: "insurance-regulatory-and-development-authority-of-india-irdai" },
  { name: "National Bank for Agriculture and Rural Development NABARD", slug: "national-bank-for-agriculture-and-rural-development-nabard" },
  { name: "Comptroller and Auditor General CAG", slug: "comptroller-and-auditor-general-cag" },
  { name: "National Institute of Food Technology Entrepreneurship and Management NIFTEM", slug: "national-institute-of-food-technology-entrepreneurship-and-management-niftem" },
  { name: "Indian Council of Medical Research ICMR", slug: "indian-council-of-medical-research-icmr" },
  { name: "All India Institute of Medical Sciences AIIMS", slug: "all-india-institute-of-medical-sciences-aiims" },
  { name: "Central Drugs Standard Control Organisation CDSCO", slug: "central-drugs-standard-control-organisation-cdsco" },
  { name: "National Pharmaceutical Pricing Authority NPPA", slug: "national-pharmaceutical-pricing-authority-nppa" },
  { name: "Automotive Research Association of India ARAI", slug: "automotive-research-association-of-india-arai" },
  { name: "Central Bureau of Investigation CBI", slug: "central-bureau-of-investigation-cbi" },
  { name: "Intelligence Bureau IB", slug: "intelligence-bureau-ib" },
  { name: "National Investigation Agency NIA", slug: "national-investigation-agency-nia" },
  { name: "Bureau of Police Research and Development BPRD", slug: "bureau-of-police-research-and-development-bprd" },
  { name: "National Crime Records Bureau NCRB", slug: "national-crime-records-bureau-ncrb" },
  { name: "Central Public Works Department CPWD", slug: "central-public-works-department-cpwd" },
  { name: "Delhi Development Authority DDA", slug: "delhi-development-authority-dda" },
  { name: "National Buildings Construction Corporation NBCC", slug: "national-buildings-construction-corporation-nbcc" },
  { name: "Press Information Bureau PIB", slug: "press-information-bureau-pib" },
  { name: "Prasar Bharati", slug: "prasar-bharati" },
  { name: "Films Division", slug: "films-division" },
  { name: "Central Water Commission CWC", slug: "central-water-commission-cwc" },
  { name: "Central Ground Water Board CGWB", slug: "central-ground-water-board-cgwb" },
  { name: "Employees Provident Fund Organisation EPFO", slug: "employees-provident-fund-organisation-epfo" },
  { name: "Employees State Insurance Corporation ESIC", slug: "employees-state-insurance-corporation-esic" },
  { name: "Directorate General of Employment DGE", slug: "directorate-general-of-employment-dge" },
  { name: "Election Commission of India ECI", slug: "election-commission-of-india-eci" },
  { name: "Supreme Court of India SCI", slug: "supreme-court-of-india-sci" },
  { name: "National Legal Services Authority NALSA", slug: "national-legal-services-authority-nalsa" },
  { name: "National Small Industries Corporation NSIC", slug: "national-small-industries-corporation-nsic" },
  { name: "Coir Board", slug: "coir-board" },
  { name: "Geological Survey of India GSI", slug: "geological-survey-of-india-gsi" },
  { name: "Indian Bureau of Mines IBM", slug: "indian-bureau-of-mines-ibm" },
  { name: "National Council for Minority Educational Institutions NCMEI", slug: "national-council-for-minority-educational-institutions-ncmei" },
  { name: "Indian Renewable Energy Development Agency IREDA", slug: "indian-renewable-energy-development-agency-ireda" },
  { name: "National Institute of Solar Energy NISE", slug: "national-institute-of-solar-energy-nise" },
  { name: "Council of Administrative Research and Training", slug: "council-of-administrative-research-and-training" },
  { name: "National Institute of Rural Development and Panchayati Raj NIRDPR", slug: "national-institute-of-rural-development-and-panchayati-raj-nirdpr" },
  { name: "Council of Scientific and Industrial Research CSIR", slug: "council-of-scientific-and-industrial-research-csir" },
  { name: "Biotechnology Industry Research Assistance Council BIRAC", slug: "biotechnology-industry-research-assistance-council-birac" },
  { name: "National Skill Development Corporation NSDC", slug: "national-skill-development-corporation-nsdc" },
  { name: "Directorate General of Training DGT", slug: "directorate-general-of-training-dgt" },
  { name: "National Human Rights Commission NHRC", slug: "national-human-rights-commission-nhrc" },
  { name: "National Institute of Public Cooperation and Child Development NIPCCD", slug: "national-institute-of-public-cooperation-and-child-development-nipccd" },
  { name: "Sports Authority of India SAI", slug: "sports-authority-of-india-sai" },
  { name: "National Sports University NSU", slug: "national-sports-university-nsu" },
  { name: "Indian Space Research Organisation ISRO", slug: "indian-space-research-organisation-isro" },
  { name: "Antrix Corporation", slug: "antrix-corporation" },
  { name: "Research Designs and Standards Organisation RDSO", slug: "research-designs-and-standards-organisation-rdso" },
  { name: "Indian Railway Catering and Tourism Corporation IRCTC", slug: "indian-railway-catering-and-tourism-corporation-irctc" },
  { name: "National Highways Authority of India NHAI", slug: "national-highways-authority-of-india-nhai" },
  { name: "Indian Academy of Highway Engineers IAHE", slug: "indian-academy-of-highway-engineers-iahe" },
  { name: "Central Institute for Research on Cotton Technology CIRCOT", slug: "central-institute-for-research-on-cotton-technology-circot" },
  { name: "National Centre for Antarctic and Ocean Research NCAOR", slug: "national-centre-for-antarctic-and-ocean-research-ncaor" },
  { name: "Central Electricity Authority CEA", slug: "central-electricity-authority-cea" },
  { name: "Central Power Research Institute CPRI", slug: "central-power-research-institute-cpri" },
  { name: "Bharat Heavy Electricals Limited BHEL", slug: "bharat-heavy-electricals-limited-bhel" },
  { name: "Steel Authority of India Limited SAIL", slug: "steel-authority-of-india-limited-sail" },
  { name: "Gas Authority of India Limited GAIL", slug: "gas-authority-of-india-limited-gail" },
  { name: "Oil and Natural Gas Corporation ONGC", slug: "oil-and-natural-gas-corporation-ongc" },
  { name: "National Thermal Power Corporation NTPC", slug: "national-thermal-power-corporation-ntpc" },
  { name: "Power Grid Corporation of India PGCIL", slug: "power-grid-corporation-of-india-pgcil" },
  { name: "Nuclear Power Corporation of India NPCIL", slug: "nuclear-power-corporation-of-india-ncpil" },
  { name: "National Aluminium Company NALCO", slug: "national-aluminium-company-nalco" },
  { name: "Bharat Electronics Limited BEL", slug: "bharat-electronics-limited-bel" },
  { name: "Bharat Petroleum Corporation Limited BPCL", slug: "bharat-petroleum-corporation-limited-bpcl" },
  { name: "Hindustan Petroleum Corporation Limited HPCL", slug: "hindustan-petroleum-corporation-limited-hpcl" },
  { name: "Indian Oil Corporation Limited IOCL", slug: "indian-oil-corporation-limited-iocl" },
  { name: "Bharat Coking Coal Limited BCCL", slug: "bharat-coking-coal-limited-bccl" },
  { name: "Central Coalfields Limited CCL", slug: "central-coalfields-limited-ccl" },
  { name: "Western Coalfields Limited WCL", slug: "western-coalfields-limited-wcl" },
  { name: "Air India Limited", slug: "air-india-limited" },
  { name: "Bharat Immunologicals and Biologicals Corporation Limited BIBCOL", slug: "bharat-immunologicals-and-biologicals-corporation-limited-bibcol" },
  { name: "Bharat Dynamics Limited BDL", slug: "bharat-dynamics-limited-bdl" },
  { name: "Bharat Earth Movers Limited BEML", slug: "bharat-earth-movers-limited-beml" },
  { name: "Central Electronics Limited CEL", slug: "central-electronics-limited-cel" },
  { name: "Chennai Petroleum Corporation Limited CPCL", slug: "chennai-petroleum-corporation-limited-cpcl" },
  { name: "Engineers India Limited EIL", slug: "engineers-india-limited-eil" },
  { name: "Ferro Scrap Nigam Limited FSNL", slug: "ferro-scrap-nigam-limited-fsnl" },
  { name: "Food Corporation of India FCI", slug: "food-corporation-of-india-fci" },
  { name: "Grid Corporation of Orissa GRIDCO", slug: "grid-corporation-of-orissa-gridco" },
  { name: "Hindustan Aeronautics Limited HAL", slug: "hindustan-aeronautics-limited-hal" },
  { name: "Hindustan Copper Limited HCL", slug: "hindustan-copper-limited-hcl" },
  { name: "Hindustan Organic Chemicals Limited HOCL", slug: "hindustan-organic-chemicals-limited-hocl" },
  { name: "Hindustan Paper Corporation Limited HPCL", slug: "hindustan-paper-corporation-limited-hpcl" },
  { name: "Hindustan Salts Limited HSL", slug: "hindustan-salts-limited-hsl" },
  { name: "Hindustan Shipyard Limited HSL", slug: "hindustan-shipyard-limited-hsl" },
  { name: "Hindustan Steelworks Construction Limited HSCL", slug: "hindustan-steelworks-construction-limited-hscl" },
  { name: "Hindustan Zinc Limited HZL", slug: "hindustan-zinc-limited-hzl" },
  { name: "Indian Tourism Development Corporation ITDC", slug: "indian-tourism-development-corporation-itdc" },
  { name: "Indian Vaccines Corporation Limited IVCOL", slug: "indian-vaccines-corporation-limited-ivcol" },
  { name: "Mahanagar Telephone Nigam Limited MTNL", slug: "mahanagar-telephone-nigam-limited-mtnl" },
  { name: "Mazagon Dock Shipbuilders Limited MDL", slug: "mazagon-dock-shipbuilders-limited-mdl" },
  { name: "Mishra Dhatu Nigam Limited MIDHANI", slug: "mishra-dhatu-nigam-limited-midhani" },
  { name: "MMTC Limited", slug: "mmtc-limited" },
  { name: "National Film Development Corporation NFDC", slug: "national-film-development-corporation-nfdc" },
  { name: "National Hydroelectric Power Corporation NHPC", slug: "national-hydroelectric-power-corporation-nhpc" },
  { name: "National Informatics Centre Services Incorporated NICSI", slug: "national-informatics-centre-services-incorporated-nicsi" },
  { name: "National Mineral Development Corporation NMDC", slug: "national-mineral-development-corporation-nmdc" },
  { name: "National Projects Construction Corporation NPCC", slug: "national-projects-construction-corporation-npcc" },
  { name: "National Seeds Corporation NSC", slug: "national-seeds-corporation-nsc" },
  { name: "National Textile Corporation NTC", slug: "national-textile-corporation-ntc" },
  { name: "NEPA Limited", slug: "nepa-limited" },
  { name: "New Delhi Television Limited NDTV", slug: "new-delhi-television-limited-ndtv" },
  { name: "NHPC Limited", slug: "nhpc-limited" },
  { name: "North Eastern Electric Power Corporation NEEPCO", slug: "north-eastern-electric-power-corporation-neepco" },
  { name: "Northern Coalfields Limited NCL", slug: "northern-coalfields-limited-ncl" },
  { name: "Oil India Limited OIL", slug: "oil-india-limited-oil" },
  { name: "Power Finance Corporation PFC", slug: "power-finance-corporation-pfc" },
  { name: "Powergrid Corporation of India Limited", slug: "powergrid-corporation-of-india-limited" },
  { name: "Prakash Industries Limited", slug: "prakash-industries-limited" },
  { name: "Rail India Technical and Economic Service RITES", slug: "rail-india-technical-and-economic-service-rites" },
  { name: "Rashtriya Chemicals and Fertilizers RCF", slug: "rashtriya-chemicals-and-fertilizers-rcf" },
  { name: "Rashtriya Ispat Nigam Limited RINL", slug: "rashtriya-ispat-nigam-limited-rinl" },
  { name: "Rural Electrification Corporation REC", slug: "rural-electrification-corporation-rec" },
  { name: "Security Printing and Minting Corporation of India SPMCI", slug: "security-printing-and-minting-corporation-of-india-spmci" },
  { name: "Shipping Corporation of India SCI", slug: "shipping-corporation-of-india-sci" },
  { name: "Shree Cement Limited", slug: "shree-cement-limited" },
  { name: "Shri Ram Transport Finance Company Srei", slug: "shri-ram-transport-finance-company-srei" },
  { name: "State Bank of India SBI", slug: "state-bank-of-india-sbi" },
  { name: "State Trading Corporation of India STC", slug: "state-trading-corporation-of-india-stc" },
  { name: "Telecom Equipment and Supplies Production Core Group TEC", slug: "telecom-equipment-and-supplies-production-core-group-tec" },
  { name: "Telecommunications Consultants India TCI", slug: "telecommunications-consultants-india-tci" },
  { name: "THDC India Limited", slug: "thdc-india-limited" },
  { name: "Tata Power Company Limited", slug: "tata-power-company-limited" },
  { name: "Utkarsha Aluminium Dhatu Nigam Limited UAL", slug: "utkarsha-aluminium-dhatu-nigam-limited-ual" },
  { name: "Visakhapatnam Steel Plant", slug: "visakhapatnam-steel-plant" },
  { name: "Water and Power Consultancy Services WAPCOS", slug: "water-and-power-consultancy-services-wapcos" },
  { name: "Welfare Commissioner of Delhi", slug: "welfare-commissioner-of-delhi" },
  { name: "Wockhardt Limited", slug: "wockhardt-limited" },
  { name: "Zee Entertainment Enterprises Limited", slug: "zee-entertainment-enterprises-limited" }
]);
    console.log("Bodies seeded successfully!");
};