import { Department } from "../models/Department.js";

export const seedDepartments = async () => {
    await Department.deleteMany();
    await Department.insertMany([
  { name: "Ministry of Agriculture and Farmers Welfare", slug: "ministry-of-agriculture-and-farmers-welfare" },
  { name: "Department of Agriculture and Farmers Welfare", slug: "department-of-agriculture-and-farmers-welfare" },
  { name: "Department of Agricultural Research and Education", slug: "department-of-agricultural-research-and-education" },
  { name: "Ministry of Animal Husbandry and Dairying", slug: "ministry-of-animal-husbandry-and-dairying" },
  { name: "Department of Fisheries", slug: "department-of-fisheries" },
  { name: "Ministry of Ayush", slug: "ministry-of-ayush" },
  { name: "Department of Ayush", slug: "department-of-ayush" },
  { name: "Ministry of Chemicals and Fertilizers", slug: "ministry-of-chemicals-and-fertilizers" },
  { name: "Department of Chemicals and Petrochemicals", slug: "department-of-chemicals-and-petrochemicals" },
  { name: "Department of Fertilisers", slug: "department-of-fertilisers" },
  { name: "Department of Pharmaceuticals", slug: "department-of-pharmaceuticals" },
  { name: "Ministry of Civil Aviation", slug: "ministry-of-civil-aviation" },
  { name: "Department of Civil Aviation", slug: "department-of-civil-aviation" },
  { name: "Ministry of Coal", slug: "ministry-of-coal" },
  { name: "Department of Coal", slug: "department-of-coal" },
  { name: "Ministry of Commerce and Industry", slug: "ministry-of-commerce-and-industry" },
  { name: "Department of Commerce", slug: "department-of-commerce" },
  { name: "Department for Promotion of Industry and Internal Trade", slug: "department-for-promotion-of-industry-and-internal-trade" },
  { name: "Ministry of Communications", slug: "ministry-of-communications" },
  { name: "Department of Posts", slug: "department-of-posts" },
  { name: "Department of Telecommunications", slug: "department-of-telecommunications" },
  { name: "Ministry of Consumer Affairs Food and Public Distribution", slug: "ministry-of-consumer-affairs-food-and-public-distribution" },
  { name: "Department of Consumer Affairs", slug: "department-of-consumer-affairs" },
  { name: "Department of Food and Public Distribution", slug: "department-of-food-and-public-distribution" },
  { name: "Ministry of Cooperation", slug: "ministry-of-cooperation" },
  { name: "Department of Cooperation", slug: "department-of-cooperation" },
  { name: "Ministry of Corporate Affairs", slug: "ministry-of-corporate-affairs" },
  { name: "Department of Corporate Affairs", slug: "department-of-corporate-affairs" },
  { name: "Ministry of Culture", slug: "ministry-of-culture" },
  { name: "Department of Culture", slug: "department-of-culture" },
  { name: "Ministry of Defence", slug: "ministry-of-defence" },
  { name: "Department of Defence Civil", slug: "department-of-defence-civil" },
  { name: "Department of Defence Production", slug: "department-of-defence-production" },
  { name: "Department of Ex-Servicemen Welfare", slug: "department-of-ex-servicemen-welfare" },
  { name: "Department of Military Affairs", slug: "department-of-military-affairs" },
  { name: "Defence Services Revenue", slug: "defence-services-revenue" },
  { name: "Capital Outlay on Defence Services", slug: "capital-outlay-on-defence-services" },
  { name: "Defence Pensions", slug: "defence-pensions" },
  { name: "Ministry of Development of North Eastern Region", slug: "ministry-of-development-of-north-eastern-region" },
  { name: "Department of North Eastern Region", slug: "department-of-north-eastern-region" },
  { name: "Ministry of Earth Sciences", slug: "ministry-of-earth-sciences" },
  { name: "Department of Earth Sciences", slug: "department-of-earth-sciences" },
  { name: "Ministry of Education", slug: "ministry-of-education" },
  { name: "Department of School Education and Literacy", slug: "department-of-school-education-and-literacy" },
  { name: "Department of Higher Education", slug: "department-of-higher-education" },
  { name: "Ministry of Electronics and Information Technology", slug: "ministry-of-electronics-and-information-technology" },
  { name: "Department of Electronics and IT", slug: "department-of-electronics-and-it" },
  { name: "Ministry of Environment Forest and Climate Change", slug: "ministry-of-environment-forest-and-climate-change" },
  { name: "Department of Environment Forest and Climate Change", slug: "department-of-environment-forest-and-climate-change" },
  { name: "Ministry of External Affairs", slug: "ministry-of-external-affairs" },
  { name: "Department of External Affairs", slug: "department-of-external-affairs" },
  { name: "Ministry of Finance", slug: "ministry-of-finance" },
  { name: "Department of Economic Affairs", slug: "department-of-economic-affairs" },
  { name: "Department of Expenditure", slug: "department-of-expenditure" },
  { name: "Department of Financial Services", slug: "department-of-financial-services" },
  { name: "Department of Investment and Public Asset Management DIPAM", slug: "department-of-investment-and-public-asset-management-dipam" },
  { name: "Department of Public Enterprises", slug: "department-of-public-enterprises" },
  { name: "Department of Revenue", slug: "department-of-revenue" },
  { name: "Direct Taxes", slug: "direct-taxes" },
  { name: "Indirect Taxes", slug: "indirect-taxes" },
  { name: "Ministry of Food Processing Industries", slug: "ministry-of-food-processing-industries" },
  { name: "Department of Food Processing Industries", slug: "department-of-food-processing-industries" },
  { name: "Ministry of Health and Family Welfare", slug: "ministry-of-health-and-family-welfare" },
  { name: "Department of Health and Family Welfare", slug: "department-of-health-and-family-welfare" },
  { name: "Department of Health Research", slug: "department-of-health-research" },
  { name: "Ministry of Heavy Industries", slug: "ministry-of-heavy-industries" },
  { name: "Department of Heavy Industries", slug: "department-of-heavy-industries" },
  { name: "Ministry of Home Affairs", slug: "ministry-of-home-affairs" },
  { name: "Department of Home", slug: "department-of-home" },
  { name: "Department of Border Management", slug: "department-of-border-management" },
  { name: "Department of Internal Security", slug: "department-of-internal-security" },
  { name: "Department of Jammu Kashmir and Sikh Affairs", slug: "department-of-jammu-kashmir-and-sikh-affairs" },
  { name: "Department of States", slug: "department-of-states" },
  { name: "Andaman and Nicobar Islands", slug: "andaman-and-nicobar-islands" },
  { name: "Chandigarh Administration", slug: "chandigarh-administration" },
  { name: "Dadra and Nagar Haveli and Daman and Diu", slug: "dadra-and-nagar-haveli-and-daman-and-diu" },
  { name: "Ladakh", slug: "ladakh" },
  { name: "Lakshadweep", slug: "lakshadweep" },
  { name: "Transfers to Delhi", slug: "transfers-to-delhi" },
  { name: "Transfers to Jammu and Kashmir", slug: "transfers-to-jammu-and-kashmir" },
  { name: "Transfers to Puducherry", slug: "transfers-to-puducherry" },
  { name: "Ministry of Housing and Urban Affairs", slug: "ministry-of-housing-and-urban-affairs" },
  { name: "Department of Housing and Urban Affairs", slug: "department-of-housing-and-urban-affairs" },
  { name: "Ministry of Information and Broadcasting", slug: "ministry-of-information-and-broadcasting" },
  { name: "Department of Information and Broadcasting", slug: "department-of-information-and-broadcasting" },
  { name: "Ministry of Jal Shakti", slug: "ministry-of-jal-shakti" },
  { name: "Department of Water Resources River Development and Ganga Rejuvenation", slug: "department-of-water-resources-river-development-and-ganga-rejuvenation" },
  { name: "Department of Drinking Water and Sanitation", slug: "department-of-drinking-water-and-sanitation" },
  { name: "Ministry of Labour and Employment", slug: "ministry-of-labour-and-employment" },
  { name: "Department of Labour and Employment", slug: "department-of-labour-and-employment" },
  { name: "Ministry of Law and Justice", slug: "ministry-of-law-and-justice" },
  { name: "Department of Justice", slug: "department-of-justice" },
  { name: "Legislative Department", slug: "legislative-department" },
  { name: "Ministry of Micro Small and Medium Enterprises", slug: "ministry-of-micro-small-and-medium-enterprises" },
  { name: "Department of MSME", slug: "department-of-msme" },
  { name: "Ministry of Mines", slug: "ministry-of-mines" },
  { name: "Department of Mines", slug: "department-of-mines" },
  { name: "Ministry of Minority Affairs", slug: "ministry-of-minority-affairs" },
  { name: "Department of Minority Affairs", slug: "department-of-minority-affairs" },
  { name: "Ministry of New and Renewable Energy", slug: "ministry-of-new-and-renewable-energy" },
  { name: "Department of New and Renewable Energy", slug: "department-of-new-and-renewable-energy" },
  { name: "Ministry of Panchayati Raj", slug: "ministry-of-panchayati-raj" },
  { name: "Department of Panchayati Raj", slug: "department-of-panchayati-raj" },
  { name: "Ministry of Parliamentary Affairs", slug: "ministry-of-parliamentary-affairs" },
  { name: "Department of Parliamentary Affairs", slug: "department-of-parliamentary-affairs" },
  { name: "Ministry of Personnel Public Grievances and Pensions", slug: "ministry-of-personnel-public-grievances-and-pensions" },
  { name: "Department of Personnel and Training", slug: "department-of-personnel-and-training" },
  { name: "Department of Pensions and Pensioners Welfare", slug: "department-of-pensions-and-pensioners-welfare" },
  { name: "Department of Administrative Reforms and Public Grievances", slug: "department-of-administrative-reforms-and-public-grievances" },
  { name: "Ministry of Petroleum and Natural Gas", slug: "ministry-of-petroleum-and-natural-gas" },
  { name: "Department of Petroleum and Natural Gas", slug: "department-of-petroleum-and-natural-gas" },
  { name: "Ministry of Planning", slug: "ministry-of-planning" },
  { name: "NITI Aayog", slug: "niti-aayog" },
  { name: "Ministry of Ports Shipping and Waterways", slug: "ministry-of-ports-shipping-and-waterways" },
  { name: "Department of Ports Shipping and Waterways", slug: "department-of-ports-shipping-and-waterways" },
  { name: "Ministry of Power", slug: "ministry-of-power" },
  { name: "Department of Power", slug: "department-of-power" },
  { name: "Staff Household and Allowances of the President", slug: "staff-household-and-allowances-of-the-president" },
  { name: "Lok Sabha", slug: "lok-sabha" },
  { name: "Rajya Sabha", slug: "rajya-sabha" },
  { name: "Secretariat of the Vice-President", slug: "secretariat-of-the-vice-president" },
  { name: "Union Public Service Commission UPSC", slug: "union-public-service-commission-upsc" },
  { name: "Central Vigilance Commission CVC", slug: "central-vigilance-commission-cvc" },
  { name: "Ministry of Railways", slug: "ministry-of-railways" },
  { name: "Department of Railways", slug: "department-of-railways" },
  { name: "Railway Board", slug: "railway-board" },
  { name: "Ministry of Road Transport and Highways", slug: "ministry-of-road-transport-and-highways" },
  { name: "Department of Road Transport and Highways", slug: "department-of-road-transport-and-highways" },
  { name: "Ministry of Rural Development", slug: "ministry-of-rural-development" },
  { name: "Department of Rural Development", slug: "department-of-rural-development" },
  { name: "Department of Land Resources", slug: "department-of-land-resources" },
  { name: "Ministry of Science and Technology", slug: "ministry-of-science-and-technology" },
  { name: "Department of Science and Technology", slug: "department-of-science-and-technology" },
  { name: "Department of Biotechnology", slug: "department-of-biotechnology" },
  { name: "Department of Scientific and Industrial Research", slug: "department-of-scientific-and-industrial-research" },
  { name: "Ministry of Skill Development and Entrepreneurship", slug: "ministry-of-skill-development-and-entrepreneurship" },
  { name: "Department of Skill Development and Entrepreneurship", slug: "department-of-skill-development-and-entrepreneurship" },
  { name: "Ministry of Social Justice and Empowerment", slug: "ministry-of-social-justice-and-empowerment" },
  { name: "Department of Social Justice and Empowerment", slug: "department-of-social-justice-and-empowerment" },
  { name: "Department of Empowerment of Persons with Disabilities", slug: "department-of-empowerment-of-persons-with-disabilities" },
  { name: "Department of Space", slug: "department-of-space" },
  { name: "Ministry of Statistics and Programme Implementation", slug: "ministry-of-statistics-and-programme-implementation" },
  { name: "Department of Statistics and Programme Implementation", slug: "department-of-statistics-and-programme-implementation" },
  { name: "National Statistical Office NSO", slug: "national-statistical-office-nso" },
  { name: "Ministry of Steel", slug: "ministry-of-steel" },
  { name: "Department of Steel", slug: "department-of-steel" },
  { name: "Ministry of Textiles", slug: "ministry-of-textiles" },
  { name: "Department of Textiles", slug: "department-of-textiles" },
  { name: "Ministry of Tourism", slug: "ministry-of-tourism" },
  { name: "Department of Tourism", slug: "department-of-tourism" },
  { name: "Ministry of Tribal Affairs", slug: "ministry-of-tribal-affairs" },
  { name: "Department of Tribal Affairs", slug: "department-of-tribal-affairs" },
  { name: "Ministry of Women and Child Development", slug: "ministry-of-women-and-child-development" },
  { name: "Department of Women and Child Development", slug: "department-of-women-and-child-development" },
  { name: "Ministry of Youth Affairs and Sports", slug: "ministry-of-youth-affairs-and-sports" },
  { name: "Department of Youth Affairs", slug: "department-of-youth-affairs" },
  { name: "Department of Sports", slug: "department-of-sports" }
]);
    console.log("Departments seeded successfully!");
};